version: '3.7'

services:
    nginx:
        image: nginx
        ports:
            - "8080:80"

        volumes:
            - ./nginx/core:/etc/nginx/conf.d
            - ./nginx/www/simple-chat:/var/www/simple-chat
            - ./nginx/Logs:/var/log/nginx/
            - ./nginx/html:/usr/share/nginx/html/

        depends_on:
            - php-fpm
            
    php-fpm:
        image: sergeylis82/php-fpm:7.4
        volumes:
            - ./nginx/www/simple-chat:/var/www/simple-chat

        depends_on:
            - mysql

    mysql:
        image: sergeylis82/sc_mysql:5.7

        environment:
            - MYSQL_ROOT_PASSWORD=Qwerty#123
            - MYSQL_DATABASE=sandbox
            - MYSQL_USER=mysql
            - MYSQL_PASSWORD=mysql
        restart: always




